// Hand-curated starter blocklist of widely-known weak passwords.
// To upgrade to the full SecLists top-10k list (recommended for production),
// run: `node scripts/fetch-blocklist.mjs` (after reviewing the script).
// HIBP k-anonymity check (lib/auth/hibp.ts) is the more comprehensive layer
// regardless of the size of this local list.
export const COMMON_PASSWORDS_RAW = [
  "123456", "password", "12345678", "qwerty", "123456789", "12345", "1234",
  "111111", "1234567", "dragon", "123123", "baseball", "abc123", "football",
  "monkey", "letmein", "shadow", "master", "666666", "qwertyuiop", "123321",
  "mustang", "1234567890", "michael", "654321", "pussy", "superman", "1qaz2wsx",
  "7777777", "fuckyou", "121212", "000000", "qazwsx", "123qwe", "killer",
  "trustno1", "jordan", "jennifer", "zxcvbnm", "asdfgh", "hunter", "buster",
  "soccer", "harley", "batman", "andrew", "tigger", "sunshine", "iloveyou",
  "fuckme", "2000", "charlie", "robert", "thomas", "hockey", "ranger", "daniel",
  "starwars", "klaster", "112233", "george", "computer", "michelle", "jessica",
  "pepper", "1111", "zxcvbn", "555555", "11111111", "131313", "freedom", "777777",
  "pass", "fuck", "maggie", "159753", "aaaaaa", "ginger", "princess", "joshua",
  "cheese", "amanda", "summer", "love", "ashley", "6969", "nicole", "chelsea",
  "biteme", "matthew", "access", "yankees", "987654321", "dallas", "austin",
  "thunder", "taylor", "matrix", "william", "corvette", "hello", "martin",
  "heather", "secret", "fucker", "merlin", "diamond", "1234qwer", "gfhjkm",
  "hammer", "silver", "222222", "88888888", "anthony", "justin", "test",
  "bailey", "q1w2e3r4t5", "patrick", "internet", "scooter", "orange", "11111",
  "golfer", "cookie", "richard", "samantha", "bigdog", "guitar", "jackson",
  "whatever", "mickey", "chicken", "sparky", "snoopy", "maverick", "phoenix",
  "camaro", "sexy", "peanut", "morgan", "welcome", "falcon", "cowboy", "ferrari",
  "samsung", "andrea", "smokey", "steelers", "joseph", "mercedes", "dakota",
  "arsenal", "eagles", "melissa", "boomer", "booboo", "spider", "nascar",
  "monster", "tigers", "yellow", "xxxxxx", "123123123", "gateway", "marina",
  "diablo", "bulldog", "qwer1234", "compaq", "purple", "hardcore", "banana",
  "junior", "hannah", "123654", "porsche", "lakers", "iceman", "money",
  "cowboys", "987654", "london", "tennis", "999999", "ncc1701", "coffee",
  "scooby", "0000", "miller", "boston", "q1w2e3r4", "fuckoff", "brandon",
  "yamaha", "chester", "mother", "forever", "johnny", "edward", "333333",
  "oliver", "redsox", "player", "nikita", "knight", "fender", "barney",
  "midnight", "please", "brandy", "chicago", "badboy", "iwantu", "slayer",
  "rangers", "charles", "angel", "flower", "bigdaddy", "rabbit", "wizard",
  "bigdick", "jasper", "enter", "rachel", "chris", "steven", "winner",
  "adidas", "victoria", "natasha", "1q2w3e4r", "jasmine", "winter", "prince",
  "panties", "marine", "ghbdtn", "fishing", "cocacola", "casper", "james",
  "232323", "raiders", "888888", "marlboro", "gandalf", "asdfasdf", "crystal",
  "87654321", "12344321", "sexsex", "golden", "blowme", "bigtits", "8675309",
  "panther", "lauren", "angela", "bitch", "spanky", "thx1138", "angels",
  "madison", "winston", "shannon", "mine", "minnie", "passw0rd", "p@ssw0rd",
  "qwerty123", "admin", "administrator", "root", "toor", "pa$$w0rd",
  "passw0rd!", "letmein123", "welcome1", "welcome123", "saffron", "saffronwealth",
] as const;
